// Code generated by codegen. DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"github.com/openchami/inventory/pkg/resources/bmc"
	"github.com/openchami/inventory/pkg/resources/boot"
	"github.com/openchami/inventory/pkg/resources/fru"
	"github.com/openchami/inventory/pkg/resources/node"
	"io"
	"net/http"
	"net/url"
	"path"
)

// Client provides access to the inventory API
type Client struct {
	baseURL    *url.URL
	httpClient *http.Client
}

// NewClient creates a new API client
func NewClient(baseURL string, httpClient *http.Client) (*Client, error) {
	if httpClient == nil {
		httpClient = http.DefaultClient
	}

	u, err := url.Parse(baseURL)
	if err != nil {
		return nil, fmt.Errorf("invalid base URL: %w", err)
	}

	return &Client{
		baseURL:    u,
		httpClient: httpClient,
	}, nil
}

// doRequest performs an HTTP request and handles the response
func (c *Client) doRequest(ctx context.Context, method, endpoint string, body interface{}, result interface{}) error {
	var reqBody io.Reader
	if body != nil {
		jsonData, err := json.Marshal(body)
		if err != nil {
			return fmt.Errorf("failed to marshal request body: %w", err)
		}
		reqBody = bytes.NewBuffer(jsonData)
	}

	u := *c.baseURL
	u.Path = path.Join(u.Path, endpoint)

	req, err := http.NewRequestWithContext(ctx, method, u.String(), reqBody)
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}

	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("failed to read response body: %w", err)
	}

	if resp.StatusCode >= 400 {
		var errorResp ErrorResponse
		if err := json.Unmarshal(respBody, &errorResp); err != nil {
			return fmt.Errorf("HTTP error %d: %s", resp.StatusCode, string(respBody))
		}
		return fmt.Errorf("API error (%d): %s", resp.StatusCode, errorResp.Error)
	}

	if result != nil {
		if err := json.Unmarshal(respBody, result); err != nil {
			return fmt.Errorf("failed to unmarshal response: %w", err)
		}
	}

	return nil
}

// GetBMCs retrieves all bmcs
func (c *Client) GetBMCs(ctx context.Context) ([]bmc.BMC, error) {
	var response BMCsResponse
	if err := c.doRequest(ctx, "GET", "/bmcs", nil, &response); err != nil {
		return nil, err
	}
	return response.Items, nil
}

// GetBMC retrieves a specific BMC by UID
func (c *Client) GetBMC(ctx context.Context, uid string) (*bmc.BMC, error) {
	var result bmc.BMC
	endpoint := fmt.Sprintf("/bmcs/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateBMC creates a new BMC
func (c *Client) CreateBMC(ctx context.Context, req CreateBMCRequest) (*bmc.BMC, error) {
	var result bmc.BMC
	if err := c.doRequest(ctx, "POST", "/bmcs", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateBMC updates an existing BMC
func (c *Client) UpdateBMC(ctx context.Context, uid string, req UpdateBMCRequest) (*bmc.BMC, error) {
	var result bmc.BMC
	endpoint := fmt.Sprintf("/bmcs/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteBMC deletes a BMC by UID
func (c *Client) DeleteBMC(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/bmcs/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetNodes retrieves all nodes
func (c *Client) GetNodes(ctx context.Context) ([]node.Node, error) {
	var response NodesResponse
	if err := c.doRequest(ctx, "GET", "/nodes", nil, &response); err != nil {
		return nil, err
	}
	return response.Items, nil
}

// GetNode retrieves a specific Node by UID
func (c *Client) GetNode(ctx context.Context, uid string) (*node.Node, error) {
	var result node.Node
	endpoint := fmt.Sprintf("/nodes/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateNode creates a new Node
func (c *Client) CreateNode(ctx context.Context, req CreateNodeRequest) (*node.Node, error) {
	var result node.Node
	if err := c.doRequest(ctx, "POST", "/nodes", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateNode updates an existing Node
func (c *Client) UpdateNode(ctx context.Context, uid string, req UpdateNodeRequest) (*node.Node, error) {
	var result node.Node
	endpoint := fmt.Sprintf("/nodes/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteNode deletes a Node by UID
func (c *Client) DeleteNode(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/nodes/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetFRUs retrieves all frus
func (c *Client) GetFRUs(ctx context.Context) ([]fru.FRU, error) {
	var response FRUsResponse
	if err := c.doRequest(ctx, "GET", "/frus", nil, &response); err != nil {
		return nil, err
	}
	return response.Items, nil
}

// GetFRU retrieves a specific FRU by UID
func (c *Client) GetFRU(ctx context.Context, uid string) (*fru.FRU, error) {
	var result fru.FRU
	endpoint := fmt.Sprintf("/frus/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateFRU creates a new FRU
func (c *Client) CreateFRU(ctx context.Context, req CreateFRURequest) (*fru.FRU, error) {
	var result fru.FRU
	if err := c.doRequest(ctx, "POST", "/frus", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateFRU updates an existing FRU
func (c *Client) UpdateFRU(ctx context.Context, uid string, req UpdateFRURequest) (*fru.FRU, error) {
	var result fru.FRU
	endpoint := fmt.Sprintf("/frus/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteFRU deletes a FRU by UID
func (c *Client) DeleteFRU(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/frus/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetBootConfigurations retrieves all bootconfigurations
func (c *Client) GetBootConfigurations(ctx context.Context) ([]boot.BootConfiguration, error) {
	var response BootConfigurationsResponse
	if err := c.doRequest(ctx, "GET", "/bootconfigurations", nil, &response); err != nil {
		return nil, err
	}
	return response.Items, nil
}

// GetBootConfiguration retrieves a specific BootConfiguration by UID
func (c *Client) GetBootConfiguration(ctx context.Context, uid string) (*boot.BootConfiguration, error) {
	var result boot.BootConfiguration
	endpoint := fmt.Sprintf("/bootconfigurations/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateBootConfiguration creates a new BootConfiguration
func (c *Client) CreateBootConfiguration(ctx context.Context, req CreateBootConfigurationRequest) (*boot.BootConfiguration, error) {
	var result boot.BootConfiguration
	if err := c.doRequest(ctx, "POST", "/bootconfigurations", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateBootConfiguration updates an existing BootConfiguration
func (c *Client) UpdateBootConfiguration(ctx context.Context, uid string, req UpdateBootConfigurationRequest) (*boot.BootConfiguration, error) {
	var result boot.BootConfiguration
	endpoint := fmt.Sprintf("/bootconfigurations/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteBootConfiguration deletes a BootConfiguration by UID
func (c *Client) DeleteBootConfiguration(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/bootconfigurations/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}
